application: neediz-ws-splitpdf
version: spliterportion
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /.*
  script: split_portion.application

libraries:
 - name: webapp2
   version: latest
 - name: jinja2
   version: latest

inbound_services:
 - channel_presence

builtins:
 - deferred: on
